"""add tes_registry static_token

Revision ID: 52bfe257d3f4
Revises: 001eb5d2ef0b
Create Date: 2026-08-05 11:19:04.437837

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '52bfe257d3f4'
down_revision: Union[str, None] = '001eb5d2ef0b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tes_registry', sa.Column('static_token', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tes_registry', 'static_token')
    # ### end Alembic commands ###
